[build]
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[context.production.environment]
  VITE_APP_ENVIRONMENT = "production"
  VITE_APP_URL = "https://proherosports.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
